### ISSUE TITLE
Website: HTTP mixed content when viewing page on HTTPS

### ISSUE THREAD

**Issue by sgnl** [1click-extensions/1click-screenshot#63]
![image](https://cloud.githubusercontent.com/assets/3915598/23004265/be714f60-f399-11e6-9f14-05c3fa9ec51d.png)

Ignore errors from ad blockers, etc 👀

**Comment by franklinyu** [comment]
I guess this has been fixed? Currently <https://openscreenshot.com/> works without issue.

**Comment by effihandelman** [comment]
Please unsubscribe me from your mailing
